baseURL = "https://marsella8.github.io/"
languageCode = "en-us"
title = "Pietro's Notes"
theme = "smol"

[params]
  subtitle = "random walking"
  dateFmt = "2006-01-02"

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = ""
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1


  [[menu.main]]
    identifier = "post-its"
    name = "Post-Its"
    url = "/post-its/"
    weight = 2



  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3



  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/Marsella8"
    weight = 10
